In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("epigenomic_dataset/epigenomes.csv")

In [3]:
for index, g in df.groupby(["cell_line", "target"]):
    if len(g)>2:
        display(g)

,accession,assembly,biological_replicates,file_format,file_size,output_type,status,url,organism,cell_line,target
26,ENCFF486PYA,hg19,"[1, 2]",bigWig,1117677730,fold change over control,archived,https://encode-public.s3.amazonaws.com/2015/10...,human,GM12878,ETV6
105,ENCFF377GCQ,hg19,"[1, 2]",bigWig,1852683009,fold change over control,archived,https://encode-public.s3.amazonaws.com/2015/11...,human,GM12878,ETV6
798,ENCFF422WMJ,hg19,"[1, 2]",bigWig,1838524283,fold change over control,released,https://encode-public.s3.amazonaws.com/2018/02...,human,GM12878,ETV6

,accession,assembly,biological_replicates,file_format,file_size,output_type,status,url,organism,cell_line,target
159,ENCFF638KYE,hg19,"[1, 2]",bigWig,2171017618,fold change over control,released,https://encode-public.s3.amazonaws.com/2016/12...,human,K562,MNT
270,ENCFF205WHE,hg19,"[1, 2]",bigWig,2240720591,fold change over control,released,https://encode-public.s3.amazonaws.com/2016/12...,human,K562,MNT
288,ENCFF757IZU,hg19,"[1, 2]",bigWig,2022513072,fold change over control,released,https://encode-public.s3.amazonaws.com/2017/05...,human,K562,MNT

,accession,assembly,biological_replicates,file_format,file_size,output_type,status,url,organism,cell_line,target
60,ENCFF423RVZ,hg19,"[1, 2]",bigWig,996578283,fold change over control,archived,https://encode-public.s3.amazonaws.com/2015/11...,human,K562,RNF2
180,ENCFF458MAY,hg19,"[1, 2]",bigWig,2647721818,fold change over control,archived,https://encode-public.s3.amazonaws.com/2016/11...,human,K562,RNF2
248,ENCFF857HEZ,hg19,"[1, 2]",bigWig,1232371252,fold change over control,released,https://encode-public.s3.amazonaws.com/2017/03...,human,K562,RNF2
398,ENCFF320VKN,hg19,"[1, 2]",bigWig,4069269344,fold change over control,released,https://encode-public.s3.amazonaws.com/2016/12...,human,K562,RNF2

In [4]:
from epigenomic_dataset import load_epigenomes

X, y = load_epigenomes(
    cell_line = "HepG2",
    dataset = "fantom",
    regions = "promoters",
    window_size = 200,
    root = "datasets" # Path where to download data
)

In [10]:
y

                                   HEPG2
chrom chromStart chromEnd  strand
chr10 100027943  100028143 -           0
      100174900  100175100 -           0
      100174957  100175157 -           0
      100206642  100206842 -           1
      100995440  100995640 -           0
...                                  ...
chrY  7141908    7142108   +           0
      7141958    7142158   +           0
      7141989    7142189   +           0
      9195271    9195471   +           0
      920851     921051    -           0

[99909 rows x 1 columns]